# Use an official Node.js runtime as a parent image
FROM node:latest

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./


# Install dependencies
RUN npm install

RUN npm uninstall bcrypt
RUN npm install bcrypt

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 5555

# Define the command to run the app
CMD ["node", "log-in.js"]
