version: '3.8'

services:
  login:
    build:
      context: ./log-in
    container_name: login_container
    env_file: ./log-in/.env
    ports:
      - "5555:5555"

  online:
    build:
      context: ./on-line
    container_name: online_container
    env_file: ./on-line/.env
    ports:
      - "8989:8989"

  chat:
    build:
      context: ./chat
    container_name: chat_container
    env_file: ./chat/.env
    ports:
      - "3000:3000"

  invite:
    build:
      context: ./invite
    container_name: invite_container
    env_file: ./invite/.env
    ports:
      - "4000:4000"