# Use the official Node.js image as the base image
FROM node

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY . .

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 4000

# Command to run the app
CMD ["node", "app.js"]